### PR TITLE
Hocr

### PR DESCRIPTION
**Pull request by jessefulton**
Hey Kyle,

I've added hooks for tesseract's HOCR functionality. Feel free to add if you'd like. Not sure how useful it will be to the OF community, but I'm using it for a project in the works.

relevant links:
http://groups.google.com/group/tesseract-ocr/browse_thread/thread/c42b551d0c24b50c
http://forum.openframeworks.cc/index.php?topic=9328.0

Thanks!
-Jesse

### CODE REVIEW

**Comment by kylemcdonald** [comment]
hey great! i'd like to make a few requests before i merge:
- (minor) it looks like you're using spaces instead of tabs for indentation
- (medium) could you rename it to `findTextHocr`. i know it looks weird, but consistency really helps, and if someone types `findText` code completion can help more :)
- (major) `setInputName()` shouldn't be public afaict. it looks like the only reason is if you want to use `findTextHocr()`, so you should add a flag to the class that checks whether `setInputName()` has been called or not whenever `findTextHocr()` is called. whenever i learn something tricky about code, i try to wrap it in a way that no one has to figure it out again unless they dig into the implementation :)

**Comment by jessefulton** [comment]
Ah, the age old spaces vs. tabs argument :)

What do you think about simply calling tess.SetInputName("") from within ofxTesseract::setup()? There shouldn't be any negative consequences and will make the implementation simpler all around.

**Comment by kylemcdonald** [comment]
the spaces/tabs thing is definitely an old argument, but i use tabs because xcode uses tabs by default -- and most contributors are using xcode, so it minimizes issues.

just calling tess.SetInputName() inside setup() is fine, i didn't know if there were any other side-effects.

**Comment by jessefulton** [comment]
Hopefully that resolves it. FWIW, seems like XCode 4 defaults to spaces instead of tabs - some wonky whitespace issues it seems.

Think I got everything though.

**Comment by kylemcdonald** [comment]
looks great. i had a suspicion about xcode 4 and spaces... thanks for confirming that.

**Pull request merged**
